### ISSUE TITLE
啥时可以升级到macOS Monterey

### ISSUE THREAD

**Issue by lrgcx** [webleon/Hackintosh-OptiPlex-7070-MFF#4]
请问大佬啥时可以升级到macOS Monterey 哈哈！

**Comment by lrgcx** [comment]
成功升级到Monterey！目前一切正常！

**Comment by rivaul** [comment]
> 成功升级到蒙特雷！目前一切正常！

大神可以共享一下你的macOS Monterey 7070mff EFI 文件出来吗？？

**Comment by lehug** [comment]
官方github里面已经是 monterey的了，但是昨晚我用我公司的新电脑试了下，不行，启动的时候卡到那不走。不知道啥原因。
特别说明，是i7-10700,买的不带固态硬盘，是供应商后期加装的netac的固态硬盘.

**Comment by webleon** [comment]
> 官方github里面已经是 monterey的了，但是昨晚我用我公司的新电脑试了下，不行，启动的时候卡到那不走。不知道啥原因。 特别说明，是i7-10700,买的不带固态硬盘，是供应商后期加装的netac的固态硬盘.

10700的话应该是7080，可以按照 Dortania 的文档调整配置。
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html

**Comment by lehug** [comment]
对不起，搞错了。我这是公司的电脑，7070和7080都有。用7070的机器，和这个配置了，结果启动的时候进度条到1/3卡着不动了。当时试着直接改了配置文件，加了-v也不显示

**Comment by wqk317** [comment]
> 试试 https://cloud.189.cn/t/FvYfEnjInUV3

@lehug 我用的就是这个, 你直接下载应该就行
