### ISSUE TITLE
求分享下 BIOS Settings via GRUB 相关的帮助文档，谢谢

### ISSUE THREAD

**Issue by lehug** [webleon/Hackintosh-OptiPlex-7070-MFF#5]
求分享下BIOS Settings via GRUB 的文档，谢谢啦，辛苦啦

**Comment by flipphos** [comment]
Just a  commnet, modGRUBShell.efi can be run as a tool under Opencore, just like other tools under the "Tools" folder.
![截屏2021-12-03 上午8 28 48](https://user-images.githubusercontent.com/11366098/144524253-b7b3729f-bf16-488c-b02f-be82380e3e1b.png)
